/*
 * generated by Xtext 2.12.0
 */
package nl.utwente.fmt.ras


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RasRuntimeModule extends AbstractRasRuntimeModule {
}
