/*
 * generated by Xtext 2.12.0
 */
package nl.utwente.fmt.ras


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RasStandaloneSetup extends RasStandaloneSetupGenerated {

	def static void doSetup() {
		new RasStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
