/*
 * generated by Xtext 2.12.0
 */
package nl.utwente.fmt.ras.validation

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RasValidator extends AbstractRasValidator {
}
