/*
 * generated by Xtext 2.12.0
 */
package nl.utwente.fmt.ras.ide

import com.google.inject.Guice
import nl.utwente.fmt.ras.RasRuntimeModule
import nl.utwente.fmt.ras.RasStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RasIdeSetup extends RasStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RasRuntimeModule, new RasIdeModule))
	}
	
}
